name: Build and test

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        vips-version: ['8.14.1']
        go-version: ['1.20']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build and test
        run: |
          docker build \
            -t nestor-sk/vimgo:ci \
            --build-arg LIBVIPS_VERSION=${{ matrix.vips-version }} \
            .
          docker run \
            --mount type=bind,source="$(pwd)",target=/pwd \
            nestor-sk/vimgo:ci \
            sh -c 'go vet . && golangci-lint run && go test -v -race -covermode=atomic -coverprofile=/pwd/covprofile'

      - name: Upload coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile